name: expenses
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.11.0+1
  charts_flutter: ^0.9.0
  font_awesome_flutter: ^8.8.1
  provider: ^3.0.0+1
  google_sign_in: ^4.4.4
  firebase_auth: ^0.11.0+1
  shared_preferences: ^0.5.7
  rect_getter: ^0.1.0
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/not_found.png
    - assets/images/finance5.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 700
